#Servidor de archivos Azure
azure:
  storage:
    container:
      name: 
        comprobante-pago
    connection:
      #string: DefaultEndpointsProtocol=https;AccountName=testaname;AccountKey=ynnrnSuLoHcROgcLmsmhuLOaOBDLLCLLw4yCPbHaSWVjA5b2jL8vUGC80VMSiSRx/WJWKXiCT7Or+AStH7AqOQ==;BlobEndpoint=https://testaname.blob.core.windows.net/;QueueEndpoint=https://testaname.queue.core.windows.net/;TableEndpoint=https://testaname.table.core.windows.net/;FileEndpoint=https://testaname.file.core.windows.net/;
      #ynnrnSuLoHcROgcLmsmhuLOaOBDLLCLLw4yCPbHaSWVjA5b2jL8vUGC80VMSiSRx/WJWKXiCT7Or+AStH7AqOQ==

      string: DefaultEndpointsProtocol=https;AccountName=anamestorage;AccountKey=OM+3ogiQCJtt1+ZlmpZHbQCz9ZowbFEARwdjoPwB7XhHTX6QeUD3KrpFOdXfS6P14eV6wLG9mWb4+AStUIluQA==;EndpointSuffix=core.windows.net